### ISSUE TITLE
Skrive notat til EPJ

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/VKP-R4#1]
Hei - siden det er flere (Førerrett, VKP+) som trenger løsning på dette use case har jeg puttet det under HelseAPI-prosjektet:

https://github.com/HL7Norway/HelseAPI/issues/7

-espen

**Comment by oaassv** [comment]
Kan vi lukke denne?

**Comment by thomiz** [comment]
Ja vi kan lukke
